# Generated by Django 4.1.5 on 2023-01-08 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chatApp6.group'),
        ),
    ]
